'use strict';
const fs = require('fs');
const path = require('path');
const { renderArticlePage } = require('./lib/article-page');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'artikel');
const SITE = 'https://www.yukaindonesia.com';
const CREDIT = 'Foto: Dokumentasi YUKA (Yayasan Ukhuwah Kaffah Amanatullah).';

const esc = (s) => String(s)
  .replace(/&/g, '&amp;')
  .replace(/"/g, '&quot;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;');
const L = (slug, text) => `<a href="${slug}">${text}</a>`;
const fig = (file, alt, caption, w, h) => `<figure><img src="../${file}" alt="${esc(alt)}" width="${w}" height="${h}" loading="lazy"><figcaption>${caption}<span class="kredit">${CREDIT}</span></figcaption></figure>`;
const P = (s) => `<p>${s}</p>`;
const H2 = (id, s) => `<h2 id="${id}">${s}</h2>`;
const H3 = (s) => `<h3>${s}</h3>`;
const ul = (items) => `<ul>${items.map((x) => `<li>${x}</li>`).join('')}</ul>`;
const faqBlock = (faq) => `${H2('faq', 'Pertanyaan yang Sering Diajukan')}${faq.map((f) => `${H3(f.q)}${P(f.a)}`).join('\n')}`;
const faq = (items) => items.map(([q, a]) => ({ q, a }));

const articles = [
  {
    slug: 'slb-itu-singkatan-dari-apa',
    titleTag: 'SLB Itu Singkatan dari Apa? Panduan untuk Orang Tua',
    metaDesc: 'SLB itu singkatan dari Sekolah Luar Biasa. Pahami fungsi, layanan, pilihan sekolah, dan cara menentukan dukungan belajar anak.',
    keywords: 'slb itu singkatan dari apa, Sekolah Luar Biasa, pendidikan anak berkebutuhan khusus, sekolah inklusi',
    ogTitle: 'SLB Itu Singkatan dari Apa? Panduan Memilih Dukungan Belajar Anak',
    ogDesc: 'Penjelasan sederhana tentang SLB, perbedaannya dengan sekolah inklusi, dan langkah orang tua mencari dukungan belajar yang sesuai.',
    datePublished: '2026-10-06T09:00:00+07:00',
    dateModified: '2026-10-11T09:00:00+07:00',
    dateDisplay: '06 Oktober 2026',
    readTime: '14 menit baca',
    category: 'Pendidikan',
    h1: 'SLB Itu Singkatan dari Apa? Memahami Sekolah Luar Biasa dan Pilihan Belajar Anak',
    crumb: 'SLB Itu Singkatan dari Apa',
    parent: { href: 'pendidikan-khusus', name: 'Pendidikan Khusus' },
    image: {
      file: 'Dokumentasi/museum-gunung-merapi-peserta-acara-foto-bersama-indoor-057.webp',
      w: 1600, h: 1200,
      alt: 'Peserta kegiatan anak dan pendamping berfoto bersama di ruang kegiatan YUKA',
      caption: 'Dokumentasi kegiatan bersama anak dan pendamping dalam suasana belajar yang ramah dan partisipatif.',
      credit: CREDIT
    },
    about: ['Sekolah Luar Biasa', 'Pendidikan khusus', 'Pendidikan inklusif'],
    tags: ['SLB', 'pendidikan khusus', 'sekolah inklusi', 'anak berkebutuhan khusus'],
    sourcesCheckedNote: 'Sumber resmi diperiksa pada 11 Oktober 2026. Nama sekolah, layanan, dan jadwal penerimaan dapat berubah, sehingga orang tua perlu melakukan konfirmasi langsung sebelum mendaftar.',
    sources: [
      { label: 'UNICEF - Inclusive education', url: 'https://www.unicef.org/education/inclusive-education' },
      { label: 'UNICEF - Children with disabilities', url: 'https://www.unicef.org/disabilities' },
      { label: 'WHO - Monitoring children\'s development in primary care services', url: 'https://www.who.int/publications/i/item/9789240012479' },
      { label: 'WHO - Improving early childhood development', url: 'https://who.int/publications/i/item/97892400020986' }
    ],
    related: [
      { href: 'pendidikan-khusus', title: 'Pendidikan Khusus: Pengertian dan Bentuk Layanannya', desc: 'Mengenal dukungan belajar yang dapat disusun berdasarkan kebutuhan dan kekuatan anak.' },
      { href: 'pendidikan-inklusi', title: 'Sekolah Inklusi dan Dukungan di Kelas', desc: 'Hal yang perlu ditanyakan saat keluarga mempertimbangkan lingkungan belajar inklusif.' },
      { href: 'program-pembelajaran-individual', title: 'Program Pembelajaran Individual', desc: 'Mengapa tujuan belajar sebaiknya dibuat spesifik, terukur, dan bermakna bagi anak.' }
    ],
    faq: faq([
      ['SLB itu singkatan dari apa?', 'SLB adalah singkatan dari Sekolah Luar Biasa, yaitu satuan pendidikan yang menyelenggarakan layanan pendidikan khusus bagi peserta didik yang membutuhkan dukungan tertentu. Bentuk layanan dan tingkat dukungannya dapat berbeda antar sekolah.'],
      ['Apakah semua anak berkebutuhan khusus harus masuk SLB?', 'Tidak. Pilihan pendidikan tidak ditentukan hanya oleh label atau diagnosis. Keluarga dapat membandingkan SLB, sekolah inklusi, dan pilihan lain berdasarkan kebutuhan belajar, komunikasi, mobilitas, jarak, kesiapan sekolah, serta suara anak.'],
      ['Apa yang perlu ditanyakan sebelum memilih SLB?', 'Tanyakan kurikulum, rasio pendamping, cara asesmen, dukungan komunikasi, fasilitas aksesibilitas, program kemandirian, penanganan perilaku, jadwal terapi bila ada, biaya, transportasi, dan mekanisme komunikasi dengan keluarga.'],
      ['Apakah SLB sama dengan tempat terapi?', 'Tidak. SLB adalah satuan pendidikan. Tempat terapi memberikan layanan rehabilitasi atau intervensi tertentu. Keduanya dapat saling berkoordinasi, tetapi fungsi, tenaga profesional, tujuan, dan cara evaluasinya berbeda.'],
      ['Bagaimana cara mengetahui sekolah cocok untuk anak?', 'Minta kunjungan atau percakapan awal, amati interaksi pendidik dengan anak, tanyakan contoh target belajar, dan perhatikan apakah sekolah mau menyesuaikan dukungan. Kecocokan bukan hanya soal gedung, tetapi juga sikap, komunikasi, dan kesinambungan program.'],
      ['Apakah orang tua perlu membawa hasil asesmen?', 'Hasil asesmen yang relevan dapat membantu sekolah memahami kekuatan dan kebutuhan anak. Bawa salinan yang diperlukan, tetapi tetap tanyakan siapa yang mengakses data, bagaimana penyimpanannya, dan apakah keluarga menerima ringkasan pembahasan.'],
      ['Kapan orang tua perlu meminta bantuan profesional?', 'Mintalah bantuan bila ada kekhawatiran tentang komunikasi, belajar, perilaku, gerak, kemandirian, atau partisipasi anak. Konsultasi tidak otomatis berarti anak harus masuk SLB. Tujuannya adalah memahami kebutuhan dan menyusun langkah yang aman.']
    ]),
    bodyHtml: ''
  },
  {
    slug: 'terapis-anak-berkebutuhan-khusus-di-solo',
    titleTag: 'Terapis Anak Berkebutuhan Khusus di Solo | Panduan',
    metaDesc: 'Panduan mencari terapis anak berkebutuhan khusus di Solo: jenis layanan, cara mengecek kredensial, biaya, rujukan, dan evaluasi.',
    keywords: 'terapis anak berkebutuhan khusus di solo, terapi anak Solo, okupasi, terapi wicara, fisioterapi anak',
    ogTitle: 'Terapis Anak Berkebutuhan Khusus di Solo: Cara Memilih Layanan',
    ogDesc: 'Langkah praktis untuk keluarga di Solo saat mencari layanan terapi anak yang aman, transparan, kolaboratif, dan sesuai tujuan keluarga.',
    datePublished: '2026-10-07T09:00:00+07:00',
    dateModified: '2026-10-11T09:00:00+07:00',
    dateDisplay: '07 Oktober 2026',
    readTime: '15 menit baca',
    category: 'Pendidikan',
    h1: 'Terapis Anak Berkebutuhan Khusus di Solo: Panduan Memilih Layanan yang Tepat',
    crumb: 'Terapis Anak Berkebutuhan Khusus di Solo',
    parent: { href: 'pendidikan-khusus', name: 'Pendidikan Khusus' },
    image: {
      file: 'Dokumentasi/21 Jan 2026/IMG_8417_latar_belakang.webp',
      w: 1920, h: 1440,
      alt: 'Anak dan pendamping mengikuti kegiatan belajar bersama di lingkungan YUKA',
      caption: 'Kegiatan bersama anak dan pendamping menunjukkan pentingnya dukungan yang terhubung dengan rutinitas sehari-hari.',
      credit: CREDIT
    },
    about: ['Terapi anak', 'Rehabilitasi anak', 'Dukungan keluarga'],
    tags: ['terapis anak', 'Solo', 'terapi wicara', 'terapi okupasi', 'fisioterapi'],
    sourcesCheckedNote: 'Sumber resmi diperiksa pada 11 Oktober 2026. Artikel ini tidak membuat daftar rekomendasi klinik tertentu. Ketersediaan layanan, jadwal, biaya, dan kewenangan profesional harus dikonfirmasi langsung kepada penyedia layanan dan fasilitas kesehatan terkait.',
    sources: [
      { label: 'WHO - Package of interventions for rehabilitation', url: 'https://www.who.int/teams/noncommunicable-diseases/sensory-functions-disability-and-rehabilitation/rehabilitation/service-delivery/package-of-interventions-for-rehabilitation' },
      { label: 'WHO - Disability and health', url: 'https://www.who.int/news-room/fact-sheets/detail/disability-and-health' },
      { label: 'CDC - Early Intervention', url: 'https://www.cdc.gov/act-early/early-intervention/index.html' },
      { label: 'WHO - Monitoring children\'s development in primary care services', url: 'https://www.who.int/publications/i/item/9789240012479' }
    ],
    related: [
      { href: 'terapi-okupasi-untuk-anak-cerebral-palsy', title: 'Terapi Okupasi untuk Anak', desc: 'Contoh fokus aktivitas fungsional dan alasan target perlu dikaitkan dengan kehidupan sehari-hari.' },
      { href: 'terapi-fisik-untuk-anak-terlambat-jalan', title: 'Terapi Fisik untuk Anak Terlambat Jalan', desc: 'Hal yang perlu dibicarakan bersama profesional saat keluarga memiliki kekhawatiran tentang gerak.' },
      { href: 'hanen-approach-terapi-bahasa-anak', title: 'Pendekatan untuk Bahasa Anak', desc: 'Dukungan komunikasi yang juga melibatkan orang tua dan rutinitas rumah.' }
    ],
    faq: faq([
      ['Di mana mencari terapis anak berkebutuhan khusus di Solo?', 'Mulailah dari dokter anak, puskesmas, rumah sakit, sekolah, komunitas keluarga, atau organisasi disabilitas yang dapat menjelaskan jalur rujukan. Gunakan situs resmi fasilitas bila tersedia, lalu hubungi langsung untuk memastikan layanan masih berjalan.'],
      ['Apa bedanya terapi wicara, okupasi, dan fisioterapi?', 'Terapi wicara dapat berfokus pada komunikasi, bahasa, suara, atau fungsi menelan sesuai kewenangan profesional. Terapi okupasi berfokus pada partisipasi dalam aktivitas bermakna, sedangkan fisioterapi banyak berkaitan dengan gerak, posisi, kekuatan, dan fungsi fisik. Kebutuhan tiap anak dapat tumpang tindih.'],
      ['Apakah anak harus punya diagnosis sebelum terapi?', 'Tidak semua konsultasi awal mensyaratkan diagnosis. Namun, penyedia layanan perlu menjelaskan proses asesmen, batas kewenangan, dan kapan rujukan medis atau psikologis diperlukan. Jangan menerima klaim bahwa satu terapi dapat memastikan diagnosis atau menyembuhkan semua kondisi.'],
      ['Bagaimana mengecek kredensial terapis?', 'Tanyakan nama lengkap, profesi, pendidikan, registrasi atau izin yang relevan, pengalaman pada tujuan layanan, supervisor bila ada, serta siapa yang menyusun dan meninjau program. Informasi harus disampaikan terbuka dan tidak boleh menekan keluarga untuk membayar paket sebelum asesmen.'],
      ['Berapa biaya terapi anak di Solo?', 'Biaya berbeda menurut jenis layanan, durasi, fasilitas, asesmen, dan frekuensi. Karena angka dapat berubah, minta rincian tertulis tentang tarif konsultasi, asesmen, sesi, pembatalan, alat, dan laporan. Bandingkan transparansi layanan, bukan hanya harga terendah.'],
      ['Berapa kali anak perlu terapi dalam seminggu?', 'Frekuensi ditentukan berdasarkan tujuan, kapasitas anak, rekomendasi profesional, kesempatan latihan di rumah, sekolah, dan kondisi keluarga. Jadwal padat tidak otomatis lebih baik. Minta indikator kemajuan dan jadwal evaluasi agar keputusan dapat disesuaikan.'],
      ['Apa tanda layanan terapi perlu dievaluasi ulang?', 'Evaluasi diperlukan bila target tidak jelas, laporan tidak pernah dibahas, anak terus menunjukkan stres tanpa rencana dukungan, keluarga tidak boleh bertanya, atau ada janji hasil pasti. Sampaikan kekhawatiran dan minta rencana perbaikan atau rujukan kedua.']
    ]),
    bodyHtml: ''
  },
  {
    slug: 'lebaran-anak-abk',
    titleTag: 'Lebaran Anak ABK: Ide Kegiatan yang Inklusif dan Nyaman',
    metaDesc: 'Ide Lebaran anak ABK yang ramah sensori: siapkan pilihan kegiatan, komunikasi, waktu istirahat, keamanan, dan peran anak.',
    keywords: 'lebaran anak ABK, kegiatan Lebaran anak berkebutuhan khusus, ramah sensori, keluarga inklusif',
    ogTitle: 'Lebaran Anak ABK: Menyiapkan Perayaan yang Inklusif dan Bermakna',
    ogDesc: 'Panduan keluarga untuk menyiapkan kegiatan Lebaran yang memberi pilihan, menjaga kenyamanan, dan tetap melibatkan anak berkebutuhan khusus.',
    datePublished: '2026-10-07T09:00:00+07:00',
    dateModified: '2026-10-11T09:00:00+07:00',
    dateDisplay: '07 Oktober 2026',
    readTime: '14 menit baca',
    category: 'Pendidikan',
    h1: 'Lebaran Anak ABK: Cara Menyiapkan Perayaan yang Inklusif dan Nyaman',
    crumb: 'Lebaran Anak ABK',
    parent: { href: 'inklusi-sosial', name: 'Inklusi Sosial' },
    image: {
      file: 'Dokumentasi/museum-gunung-merapi-keluarga-besar-foto-bersama-istana-028.webp',
      w: 1664, h: 1248,
      alt: 'Keluarga dan anak-anak berfoto bersama dalam kegiatan YUKA di ruang yang ramah keluarga',
      caption: 'Kegiatan bersama dapat menjadi menyenangkan ketika anak diberi pilihan, waktu jeda, dan dukungan yang mudah dipahami.',
      credit: CREDIT
    },
    about: ['Inklusi sosial', 'Anak berkebutuhan khusus', 'Kegiatan keluarga'],
    tags: ['Lebaran', 'anak ABK', 'ramah sensori', 'keluarga inklusif'],
    sourcesCheckedNote: 'Sumber resmi diperiksa pada 11 Oktober 2026. Setiap anak memiliki kebutuhan yang berbeda. Rencana keluarga perlu disesuaikan dengan komunikasi, kesehatan, keamanan, preferensi, dan persetujuan anak.',
    sources: [
      { label: 'UNICEF - Inclusive education', url: 'https://www.unicef.org/education/inclusive-education' },
      { label: 'UNICEF - Children with disabilities', url: 'https://www.unicef.org/disabilities' },
      { label: 'UNICEF - Guidance on including children with disabilities', url: 'https://www.unicef.org/supply/documents/guidance-including-children-disabilities-education-kit-handbook' },
      { label: 'WHO - Improving early childhood development', url: 'https://who.int/publications/i/item/97892400020986' }
    ],
    related: [
      { href: 'inklusi-sosial', title: 'Inklusi Sosial Adalah', desc: 'Memahami partisipasi yang setara dan dukungan yang mengurangi hambatan.' },
      { href: 'teori-inklusi-sosial', title: 'Teori Inklusi Sosial', desc: 'Kerangka untuk melihat apakah kegiatan benar-benar membuka ruang bagi semua.' },
      { href: 'liburan-dengan-anak-berkebutuhan-khusus', title: 'Liburan dengan Anak Berkebutuhan Khusus', desc: 'Cara membuat rencana perjalanan yang lentur dan tidak memaksa.' }
    ],
    faq: faq([
      ['Apa kegiatan Lebaran yang cocok untuk anak ABK?', 'Kegiatan yang dapat dipilih antara lain membuat kartu ucapan, menyiapkan hidangan sederhana, melihat foto keluarga, salat atau silaturahmi dengan durasi yang disepakati, bermain tenang, dan berbagi cerita. Pilihan terbaik bergantung pada minat dan kebutuhan anak.'],
      ['Bagaimana menyiapkan anak sebelum silaturahmi?', 'Gunakan cerita sosial, foto tempat, jadwal visual, atau latihan singkat tentang siapa yang akan ditemui. Jelaskan urutan kegiatan dengan bahasa yang dapat dipahami anak. Sertakan rencana pulang, tempat istirahat, dan cara meminta jeda.'],
      ['Bagaimana membuat suasana Lebaran lebih ramah sensori?', 'Kurangi suara yang tidak perlu, sediakan sudut tenang, pilih waktu kunjungan yang tidak terlalu padat, izinkan alat bantu regulasi, siapkan pakaian yang nyaman, dan jangan memaksa anak menyentuh, mencium, atau memeluk orang lain.'],
      ['Apakah anak harus ikut semua acara keluarga?', 'Tidak. Inklusi bukan berarti semua orang harus mengikuti kegiatan yang sama dengan cara yang sama. Anak boleh ikut sebagian, mengamati, beristirahat, atau memilih aktivitas lain selama tetap aman dan dihargai.'],
      ['Bagaimana mengajak keluarga besar mendukung anak?', 'Sampaikan kebutuhan anak sebelum acara, gunakan kalimat singkat, dan bagikan aturan sederhana seperti tidak memaksa kontak fisik, tidak mengejek cara bicara, serta memberi waktu untuk menjawab. Tunjuk satu orang dewasa sebagai pendamping utama.'],
      ['Apa yang dilakukan jika anak kewalahan saat Lebaran?', 'Kurangi tuntutan, pindahkan anak ke tempat yang lebih tenang, tawarkan pilihan sederhana, bantu komunikasi, dan beri waktu pemulihan. Hindari mempermalukan atau mengancam. Setelah keadaan stabil, catat pemicu dan dukungan yang membantu.'],
      ['Bagaimana menjaga keamanan anak saat banyak tamu?', 'Tentukan orang dewasa yang bertanggung jawab, kenalkan batas area aman, simpan obat atau benda berbahaya, periksa pintu dan akses keluar, serta gunakan identitas darurat bila memang dibutuhkan. Rencana harus menghormati privasi anak.']
    ]),
    bodyHtml: ''
  }
];

articles[0].bodyHtml = `
${P('<strong>Jawaban singkat:</strong> SLB adalah singkatan dari Sekolah Luar Biasa. Namun, memahami kepanjangan saja belum cukup untuk menentukan sekolah yang tepat. Keluarga perlu melihat kebutuhan belajar, komunikasi, kemandirian, kesehatan, jarak, biaya, serta kesiapan lingkungan pendidikan. Artikel ini membantu orang tua membedakan istilah dan menyiapkan pertanyaan sebelum berkunjung.')}
<div class="toc"><h3>Daftar Isi</h3><ol><li><a href="#pengertian">Apa itu SLB?</a></li><li><a href="#fungsi">Fungsi dan layanan</a></li><li><a href="#pilihan">SLB, sekolah inklusi, dan pilihan lain</a></li><li><a href="#kunjungan">Cara menilai sekolah</a></li><li><a href="#kolaborasi">Kolaborasi dengan keluarga</a></li><li><a href="#langkah">Langkah pendaftaran</a></li><li><a href="#faq">Pertanyaan yang Sering Diajukan</a></li></ol></div>
${H2('pengertian', 'SLB itu singkatan dari apa?')}
${P('SLB merupakan singkatan dari Sekolah Luar Biasa. Istilah ini digunakan untuk menyebut satuan pendidikan yang menyiapkan layanan pendidikan khusus. Dalam percakapan sehari-hari, SLB sering dianggap sebagai tempat untuk semua anak penyandang disabilitas, padahal setiap sekolah dapat memiliki jenjang, program, tenaga pendidik, fasilitas, dan cara dukungan yang berbeda. Karena itu, arti singkatan perlu diikuti dengan pertanyaan yang lebih penting: dukungan seperti apa yang tersedia untuk anak tertentu?')}
${P(`Pendidikan khusus bukan sekadar memindahkan anak ke ruang yang berbeda. Tujuannya adalah membantu anak belajar, berkomunikasi, membangun kemandirian, dan berpartisipasi dalam kehidupan bersama. Prinsip ini sejalan dengan penjelasan ${L('https://www.unicef.org/education/inclusive-education', 'UNICEF tentang pendidikan inklusif')}, yang menekankan kesempatan belajar dan berkembang bagi semua anak, termasuk anak penyandang disabilitas. Keluarga dapat memakai prinsip tersebut saat menilai apakah layanan sekolah menghargai potensi dan suara anak.`)}
${fig('Dokumentasi/artikel/apa-yang-dimaksud-dengan-sekolah-luar-biasa-dokumentasi.webp', 'Suasana kegiatan belajar anak dan pendamping dalam lingkungan pendidikan khusus', 'Lingkungan belajar yang baik memberi ruang bagi anak untuk belajar dengan cara yang dapat diakses dan bermakna.', 900, 675)}
${H2('fungsi', 'Apa fungsi SLB bagi peserta didik?')}
${P('Fungsi SLB dapat mencakup pembelajaran akademik, pengembangan komunikasi, latihan kemandirian, keterampilan sosial, aktivitas fisik, serta persiapan mengikuti kegiatan masyarakat. Porsi setiap bagian tidak sama untuk semua anak. Seorang anak mungkin memerlukan dukungan komunikasi yang intensif, sementara anak lain lebih membutuhkan adaptasi materi, latihan mobilitas, atau struktur rutinitas yang konsisten. Program yang baik menjelaskan tujuan dalam bahasa yang dapat dipahami keluarga dan meninjau kemajuan secara berkala.')}
${P('Orang tua sebaiknya meminta contoh target yang dapat diamati. Target seperti "menjadi lebih pintar" terlalu umum. Target yang lebih informatif misalnya anak dapat meminta bantuan dengan cara yang disepakati, menyelesaikan dua langkah kegiatan makan, mengikuti instruksi bergambar, atau berpindah ruang dengan dukungan yang makin berkurang. Target tetap perlu disusun oleh pendidik dan profesional yang berwenang setelah memahami anak, bukan diambil mentah dari daftar internet.')}
${fig('Dokumentasi/artikel/peer-tutoring-di-kelas-inklusi-kegiatan.webp', 'Anak-anak mengikuti kegiatan belajar bersama dengan pendamping', 'Kegiatan bersama dapat melatih komunikasi, giliran, kerja sama, dan rasa memiliki terhadap kelompok.', 900, 675)}
${H2('pilihan', 'SLB, sekolah inklusi, dan pilihan pendidikan lain')}
${P('SLB bukan satu-satunya pilihan. Sekolah inklusi berupaya membuat anak belajar bersama teman sebaya dengan dukungan dan penyesuaian yang diperlukan. Ada pula keluarga yang mempertimbangkan sekolah umum dengan dukungan tambahan, program pendidikan jarak jauh, atau kombinasi layanan pendidikan dan terapi. Tidak ada pilihan yang otomatis paling baik untuk semua anak. Pilihan perlu dilihat sebagai keputusan yang dapat dievaluasi, bukan label seumur hidup.')}
${P(`Saat membandingkan sekolah, lihat kecocokan antara kebutuhan anak dan dukungan yang benar-benar tersedia. ${L('https://www.unicef.org/disabilities', 'UNICEF menjelaskan bahwa anak penyandang disabilitas membutuhkan kesempatan untuk berpartisipasi')}, bukan hanya hadir secara fisik. Tanyakan bagaimana sekolah mengikutsertakan anak dalam pelajaran, istirahat, kegiatan seni, olahraga, kunjungan, dan komunikasi dengan teman. Perhatikan pula apakah anak diberi cara untuk menyampaikan pilihan atau penolakan.`)}
<table><thead><tr><th>Hal yang dibandingkan</th><th>Pertanyaan untuk keluarga</th><th>Bukti yang dicari</th></tr></thead><tbody><tr><td>Tujuan belajar</td><td>Apa target tiga bulan pertama?</td><td>Target tertulis dan cara menilai kemajuan</td></tr><tr><td>Akses komunikasi</td><td>Bagaimana anak menyampaikan kebutuhan?</td><td>Gambar, gestur, alat bantu, atau strategi komunikasi</td></tr><tr><td>Partisipasi</td><td>Apakah anak mengikuti kegiatan kelas dan sekolah?</td><td>Penyesuaian aktivitas, bukan hanya ruang terpisah</td></tr><tr><td>Kolaborasi</td><td>Kapan keluarga menerima umpan balik?</td><td>Jadwal komunikasi dan catatan perkembangan</td></tr></tbody></table>
${H2('kunjungan', 'Cara menilai SLB sebelum mendaftar')}
${P('Buat daftar pertanyaan sebelum kunjungan agar percakapan tidak berhenti pada biaya dan jadwal. Tanyakan jenjang yang tersedia, jumlah anak dalam kelas, latar belakang pendidik, pelatihan pendamping, sistem asesmen, dukungan perilaku positif, fasilitas sanitasi, akses kursi roda bila diperlukan, serta prosedur ketika anak sakit atau mengalami kelelahan. Mintalah izin untuk melihat satu kegiatan yang sedang berjalan, bukan hanya ruang kosong yang sudah ditata.')}
${P('Amati bahasa yang digunakan staf. Apakah mereka menggambarkan anak melalui kekuatan dan kebutuhan dukungan, atau hanya menyebut masalah? Apakah mereka menjelaskan cara menjaga privasi data? Apakah anak diizinkan menolak aktivitas yang membuatnya tidak nyaman dengan cara yang aman? Jawaban atas pertanyaan ini sering lebih bermakna daripada brosur. Jika sekolah menjanjikan hasil pasti, meminta pembayaran besar sebelum asesmen, atau melarang orang tua bertanya, keluarga berhak meminta penjelasan tertulis dan mencari pendapat kedua.')}
${fig('Dokumentasi/artikel/buddy-system-untuk-anak-abk-di-sekolah-kegiatan-bersama.webp', 'Anak dan pendamping melakukan kegiatan bersama dalam lingkungan yang mendukung', 'Pendampingan yang baik membantu anak berpartisipasi tanpa mengambil alih seluruh aktivitas.', 1200, 900)}
${H2('kolaborasi', 'Peran keluarga setelah anak bersekolah')}
${P('Keluarga adalah sumber informasi penting tentang komunikasi, minat, pemicu stres, pola tidur, makanan, dan kegiatan yang sudah berhasil di rumah. Sampaikan informasi secara ringkas dan pilih hal yang relevan dengan tujuan belajar. Sekolah juga perlu memberi tahu keluarga apa yang dilatih, dukungan apa yang dipakai, serta bagaimana keluarga dapat mengulanginya secara wajar tanpa menjadikan rumah seperti ruang ujian.')}
${P(`Kolaborasi dapat terhubung dengan ${L('program-pembelajaran-individual', 'program pembelajaran individual')} dan layanan lain seperti ${L('intervensi-dini', 'intervensi dini')}. Bila anak juga mengikuti terapi, minta izin untuk berbagi ringkasan tujuan yang relevan, bukan seluruh catatan kesehatan. ${L('asesmen-abk', 'Asesmen anak berkebutuhan khusus')} sebaiknya dipahami sebagai proses mengumpulkan informasi untuk merancang dukungan, bukan sebagai alat untuk membatasi harapan.`)}
${fig('Dokumentasi/artikel/strategi-mengajar-anak-autis-di-kelas-pendampingan.webp', 'Pendidik mendampingi anak dalam kegiatan belajar dengan arahan yang terstruktur', 'Dukungan yang terstruktur dapat diubah sedikit demi sedikit ketika anak semakin mandiri.', 900, 675)}
${H2('langkah', 'Langkah praktis memilih pendidikan')}
${P('Mulailah dengan menulis kebutuhan prioritas anak dalam tiga sampai lima kalimat. Catat apa yang sudah dapat dilakukan, kapan anak membutuhkan bantuan, cara komunikasi yang dipahami, dan lingkungan yang membuatnya tenang. Setelah itu, buat daftar dua atau tiga sekolah untuk dihubungi. Bandingkan jawaban menggunakan kriteria yang sama agar keputusan tidak hanya dipengaruhi kesan pertama atau rekomendasi media sosial.')}
${ul(['Minta informasi resmi tentang program, jadwal, biaya, dan proses penerimaan.', 'Jadwalkan percakapan dengan pihak sekolah dan, bila memungkinkan, kunjungan.', 'Bawa pertanyaan tentang komunikasi, asesmen, aksesibilitas, keselamatan, dan partisipasi.', 'Tulis kesepakatan awal tentang target, cara komunikasi, dan jadwal evaluasi.', 'Evaluasi kecocokan setelah masa adaptasi, lalu ubah dukungan bila diperlukan.'])}
${P(`Memahami ${L('pendidikan-khusus', 'pendidikan khusus')} membantu keluarga berbicara dengan sekolah secara lebih jelas, tetapi tidak menggantikan konsultasi profesional. Jika ada kekhawatiran perkembangan, kesehatan, atau keselamatan, mintalah rujukan kepada tenaga yang sesuai. Tujuan akhirnya bukan mengejar nama sekolah tertentu, melainkan memastikan anak mendapatkan kesempatan belajar yang aman, bermartabat, dan bermakna.`)}
${P('Ada beberapa hal administratif yang juga layak dipastikan sejak awal. Tanyakan dokumen penerimaan, jadwal observasi, masa adaptasi, mekanisme antar jemput, seragam, kegiatan luar kelas, serta siapa yang dihubungi saat anak tidak hadir. Bila sekolah meminta hasil pemeriksaan atau dokumen kesehatan, tanyakan tujuan penggunaannya dan bagaimana keluarga dapat memperbarui informasi. Keluarga tidak perlu membagikan data yang tidak berkaitan dengan dukungan pendidikan.')}
${P('Perubahan sekolah atau kelas dapat menjadi proses emosional. Anak mungkin membutuhkan foto guru, kunjungan singkat, jadwal visual, atau masa percobaan dengan durasi pendek. Catat respons anak setelah kunjungan, bukan hanya komentar orang dewasa. Tidur memburuk, penolakan terus menerus, atau kecemasan yang meningkat perlu dibicarakan. Sebaliknya, minat untuk kembali, komunikasi yang lebih mudah, atau kemandirian yang bertambah dapat menjadi tanda lingkungan mulai terasa aman. Semua pengamatan perlu dibaca bersama profesional, bukan dijadikan diagnosis mandiri.')}
${P(`Jika keluarga masih ragu, buat matriks sederhana berisi empat kolom: kebutuhan anak, dukungan yang ditawarkan, bukti yang dilihat, dan pertanyaan yang belum terjawab. Bandingkan dua atau tiga pilihan secara tenang. ${L('program-pembelajaran-individual', 'Program pembelajaran individual')} dapat menjadi bahan diskusi tentang tujuan, tetapi format tiap sekolah mungkin berbeda. Yang paling penting adalah ada kesepakatan yang bisa ditinjau, bukan dokumen yang hanya disimpan di lemari.`)}
${P('Perhatikan pula cara sekolah membicarakan kemandirian. Kemandirian tidak berarti anak harus melakukan semua hal tanpa bantuan. Kemandirian dapat berarti memilih alat, meminta jeda, memakai strategi yang sudah dilatih, atau menyelesaikan satu bagian dari kegiatan. Dukungan yang tepat membuat bantuan dapat dikurangi atau diubah ketika kemampuan anak berkembang. Tanyakan apakah sekolah memiliki cara mencatat bantuan yang dibutuhkan, karena catatan itu membantu keluarga melihat perubahan yang tidak selalu tampak dari nilai akademik.')}
${P('Kegiatan istirahat, makan, dan bermain juga bagian dari pendidikan. Anak mungkin belajar bergiliran di halaman, mengatur barang, mengikuti aturan keselamatan, atau mengenali kapan harus meminta tolong. Jika seluruh waktu di sekolah hanya diisi tugas meja, keluarga boleh bertanya bagaimana sekolah melatih keterampilan yang dibutuhkan di luar kelas. Sebaliknya, kegiatan praktis perlu tetap diberi tujuan dan tidak boleh menjadi alasan untuk mengurangi kesempatan anak mempelajari konsep akademik yang sesuai.')}
${P('Keluarga perlu memisahkan dua pertanyaan: apakah sekolah memiliki sumber daya saat ini, dan apakah sekolah bersedia merencanakan perbaikan. Tidak semua sekolah langsung memiliki semua alat. Namun, sekolah seharusnya dapat menjelaskan prioritas, batasan, dan cara mencari solusi. Jawaban yang jujur lebih berguna daripada janji besar. Jika kebutuhan anak berada di luar kapasitas sekolah, rujukan yang jelas dan komunikasi yang sopan tetap merupakan bentuk layanan yang bertanggung jawab.')}
${P('Pada akhirnya, istilah SLB hanya pintu masuk untuk memahami pilihan. Anak bukan singkatan, kategori, atau berkas pendaftaran. Anak memiliki minat, hubungan, rasa humor, cara belajar, dan hak untuk dihormati. Saat keluarga berkunjung, bawa pertanyaan, waktu, dan kesediaan mendengar suara anak. Keputusan yang baik dapat berubah seiring usia dan kebutuhan. Evaluasi berkala membuat pendidikan tetap relevan dan mencegah keluarga merasa harus mempertahankan pilihan yang sudah tidak mendukung.')}
${P('Tanyakan juga bagaimana sekolah menangani transisi harian. Perpindahan dari rumah ke kelas, pergantian guru, waktu makan, dan kegiatan luar ruangan sering memerlukan dukungan yang berbeda. Anak dapat dibantu dengan tanda visual, benda penghubung dari rumah, atau salam yang konsisten. Rencana sederhana ini sebaiknya diketahui semua pendamping agar anak tidak menerima instruksi yang saling bertentangan.')}
${P('Keluarga tidak perlu menunggu masalah besar untuk mengevaluasi layanan. Pertemuan singkat setiap beberapa minggu dapat membahas satu target, satu hal yang berhasil, dan satu perubahan kecil. Jika percakapan selalu berisi kekurangan anak tanpa membahas dukungan, minta agar formatnya diperbaiki. Sekolah dan keluarga adalah mitra yang sama-sama bertanggung jawab menjaga keselamatan, kesempatan belajar, serta martabat anak.')}
${P('Dokumentasikan kesepakatan melalui pesan atau catatan ringkas setelah pertemuan. Catatan ini membantu ketika ada pergantian guru, pendamping, atau jadwal. Gunakan bahasa faktual seperti "anak membutuhkan contoh visual sebelum berpindah kegiatan" dan hindari label yang merendahkan. Dengan catatan yang jelas, keluarga dapat memantau apakah dukungan benar-benar dilakukan dan menyampaikan koreksi tanpa harus mengulang seluruh cerita setiap kali bertemu.')}
${P(`Untuk memperluas bacaan, lihat ${L('slb-adalah', 'pengertian SLB')}, ${L('sekolah-slb-untuk-anak-apa', 'SLB untuk anak seperti apa')}, ${L('slb-terdekat', 'cara mencari SLB terdekat')}, dan ${L('ijazah-slb-setara-apa', 'pertanyaan tentang ijazah SLB')}. Gunakan artikel tersebut sebagai peta pertanyaan, lalu konfirmasi informasi penerimaan kepada sekolah atau dinas pendidikan yang berwenang.`)}
${faqBlock(articles[0].faq)}
`;

articles[1].bodyHtml = `
${P('<strong>Jawaban singkat:</strong> Mencari terapis anak berkebutuhan khusus di Solo sebaiknya dimulai dari tujuan yang jelas, jalur rujukan yang dapat dipertanggungjawabkan, dan pemeriksaan kredensial. Jangan memilih hanya karena janji hasil cepat atau paket paling murah. Layanan yang baik menjelaskan asesmen, target fungsional, keterlibatan keluarga, biaya, serta jadwal evaluasi.')}
<div class="toc"><h3>Daftar Isi</h3><ol><li><a href="#mulai">Mulai dari kebutuhan anak</a></li><li><a href="#jenis">Jenis layanan terapi</a></li><li><a href="#rujukan">Jalur mencari layanan di Solo</a></li><li><a href="#cek">Cara mengecek penyedia</a></li><li><a href="#sesi">Apa yang terjadi dalam sesi</a></li><li><a href="#evaluasi">Evaluasi dan biaya</a></li><li><a href="#faq">Pertanyaan yang Sering Diajukan</a></li></ol></div>
${H2('mulai', 'Mulai dari kebutuhan dan tujuan anak')}
${P('Istilah terapi dapat terdengar luas, sedangkan keluarga biasanya datang dengan pertanyaan sangat praktis: anak sulit menyampaikan keinginan, belum nyaman memakai alat makan, mudah jatuh, kesulitan mengikuti instruksi, atau tidak bisa ikut bermain dengan teman. Tulis contoh kejadian sehari-hari, kapan terjadi, apa yang sudah dicoba, dan dukungan yang membantu. Catatan seperti ini lebih berguna daripada hanya menyebut label kondisi.')}
${P(`Tujuan terapi sebaiknya berhubungan dengan partisipasi. ${L('https://www.who.int/teams/noncommunicable-diseases/sensory-functions-disability-and-rehabilitation/rehabilitation/service-delivery/package-of-interventions-for-rehabilitation', 'WHO menjelaskan layanan rehabilitasi')} sebagai rangkaian dukungan yang perlu terhubung dengan kebutuhan orang dan lingkungan, bukan sekadar latihan terpisah. Karena itu, tanyakan bagaimana keterampilan dari ruang terapi akan dipakai di rumah, sekolah, tempat ibadah, atau ruang bermain.`)}
${fig('Dokumentasi/artikel/terapi-bermain-child-centered-play-therapy-kegiatan.webp', 'Anak mengikuti aktivitas bermain dengan dukungan pendamping', 'Aktivitas yang bermakna dapat menjadi kesempatan untuk melatih komunikasi, regulasi, dan partisipasi.', 960, 720)}
${H2('jenis', 'Jenis layanan yang mungkin dibutuhkan')}
${P('Terapi wicara dapat mencakup komunikasi reseptif dan ekspresif, artikulasi, komunikasi augmentatif, serta aspek menelan sesuai pendidikan dan kewenangan profesional. Terapi okupasi biasanya melihat aktivitas sehari-hari, keterampilan tangan, pemrosesan sensori, bermain, dan kemandirian. Fisioterapi dapat berfokus pada gerak, postur, keseimbangan, kekuatan, serta cara anak berpindah atau beraktivitas dengan lebih aman. Psikologi, pedagogi khusus, dan layanan medis juga dapat berperan sesuai kebutuhan.')}
${P('Nama layanan bukan jaminan kecocokan. Dua anak yang sama-sama mengalami kesulitan bicara bisa memerlukan target berbeda. Satu anak mungkin perlu sistem komunikasi alternatif, sementara anak lain membutuhkan dukungan memahami giliran percakapan. Terapis perlu menjelaskan alasan pemilihan metode, indikator kemajuan, risiko, dan kapan strategi harus dihentikan atau diubah. Keluarga boleh meminta penjelasan dengan bahasa sederhana.')}
<table><thead><tr><th>Kebutuhan yang diamati</th><th>Pertanyaan awal</th><th>Profesional yang mungkin terlibat</th></tr></thead><tbody><tr><td>Komunikasi dan bahasa</td><td>Bagaimana anak meminta, menjawab, dan memahami?</td><td>Terapis wicara, psikolog, pendidik khusus</td></tr><tr><td>Aktivitas harian</td><td>Bagian mana dari makan, berpakaian, atau bermain yang sulit?</td><td>Terapis okupasi, pendidik, keluarga</td></tr><tr><td>Gerak dan posisi</td><td>Bagaimana anak berpindah dan menjaga keseimbangan?</td><td>Fisioterapis, dokter, terapis okupasi</td></tr><tr><td>Regulasi dan perilaku</td><td>Apa pemicu stres dan dukungan yang membantu?</td><td>Psikolog, pendidik, tim terapi</td></tr></tbody></table>
${H2('rujukan', 'Jalur mencari layanan terapi di Solo')}
${P('Keluarga di Solo dapat memulai dari puskesmas, rumah sakit, dokter anak, sekolah, atau komunitas keluarga. Tanyakan apakah fasilitas memiliki layanan tumbuh kembang, rehabilitasi medik, psikologi, terapi wicara, terapi okupasi, atau rujukan ke penyedia yang sesuai. Gunakan situs resmi fasilitas atau nomor kontak resmi, bukan hanya unggahan lama. Jadwal, tenaga, dan cakupan layanan dapat berubah sehingga konfirmasi langsung tetap diperlukan.')}
${P(`Bila anak sudah bersekolah, minta guru menjelaskan situasi yang terlihat di kelas. Catatan sekolah tidak menggantikan asesmen klinis, tetapi dapat membantu keluarga menyusun pertanyaan. ${L('https://www.who.int/news-room/fact-sheets/detail/disability-and-health', 'WHO mengingatkan bahwa disabilitas berhubungan dengan interaksi antara kondisi kesehatan dan lingkungan')}. Artinya, dukungan dapat berupa perubahan cara mengajar, alat bantu, atau penyesuaian lingkungan, bukan hanya sesi dengan terapis.`)}
${fig('Dokumentasi/artikel/terapi-integrasi-sensorik-di-rumah-memeras-lemon.webp', 'Aktivitas rumah yang melibatkan tangan dan indra dengan pendampingan orang dewasa', 'Latihan yang terkait dengan rutinitas rumah dapat membantu keluarga melihat manfaat keterampilan di luar ruang terapi.', 900, 675)}
${H2('cek', 'Cara mengecek penyedia layanan')}
${P('Sebelum membuat janji, tanyakan nama profesional yang akan menangani anak, pendidikan dan registrasi yang relevan, pengalaman pada tujuan yang keluarga sampaikan, durasi asesmen, format laporan, serta siapa yang melakukan supervisi. Penyedia yang transparan tidak keberatan menjelaskan batas layanan. Keluarga juga berhak mengetahui apakah sesi dilakukan individu atau kelompok, siapa saja yang boleh berada di ruangan, dan bagaimana data anak disimpan.')}
${P('Waspadai janji seperti sembuh total dalam jumlah sesi tertentu, larangan berkonsultasi dengan dokter, keharusan membeli alat mahal, atau penggunaan rasa takut agar keluarga segera membayar. Tidak semua pendekatan memiliki bukti yang sama, dan tidak semua layanan cocok untuk setiap anak. Minta waktu untuk mempertimbangkan paket. Jika jawaban tidak jelas, cari pendapat kedua dari fasilitas atau profesional lain.')}
${fig('Dokumentasi/artikel/hanen-approach-terapi-bahasa-anak-dokumentasi.webp', 'Pendamping berinteraksi dengan anak dalam kegiatan yang mendukung komunikasi', 'Keterlibatan orang tua membantu strategi komunikasi berlanjut dalam aktivitas sehari-hari.', 900, 675)}
${H2('sesi', 'Apa yang seharusnya terjadi dalam asesmen dan sesi terapi?')}
${P('Asesmen awal seharusnya memberi ruang bagi keluarga untuk menceritakan tujuan, rutinitas, riwayat layanan, kekuatan, dan kekhawatiran. Profesional dapat mengamati permainan atau aktivitas, mengajukan pertanyaan, memakai alat ukur yang sesuai, lalu menyampaikan temuan dengan batasan yang jujur. Satu pertemuan tidak selalu cukup untuk menyimpulkan kebutuhan anak. Bila informasi belum cukup, rencana dapat berupa observasi tambahan atau rujukan.')}
${P('Sesi terapi yang baik tidak selalu terlihat seperti anak duduk diam mengerjakan lembar kerja. Anak dapat berlatih meminta giliran melalui permainan, memperbaiki posisi tubuh saat meraih benda, belajar memakai sendok, atau mencoba cara berkomunikasi yang lebih efektif. Yang penting, keluarga memahami tujuan, cara memberi dukungan, dan tanda anak mulai lelah. Anak tidak boleh dipaksa melewati rasa sakit atau ketakutan tanpa rencana keselamatan.')}
${fig('Dokumentasi/artikel/terapi-fisik-untuk-anak-terlambat-jalan-dokumentasi.webp', 'Pendamping mendukung latihan gerak anak dalam aktivitas yang terarah', 'Latihan gerak perlu disesuaikan dengan kemampuan, keamanan, dan tujuan fungsional anak.', 900, 675)}
${H2('evaluasi', 'Evaluasi, jadwal, dan biaya')}
${P('Tanyakan kapan evaluasi dilakukan dan indikator apa yang digunakan. Kemajuan dapat terlihat dari frekuensi anak meminta bantuan, durasi mengikuti kegiatan, kemampuan menyelesaikan langkah, atau berkurangnya bantuan yang dibutuhkan. Kemajuan tidak selalu berarti anak melakukan tugas dengan cara yang sama seperti anak lain. Ukuran yang baik adalah apakah anak lebih aman, lebih mampu berkomunikasi, dan lebih dapat berpartisipasi dalam aktivitas bermakna.')}
${P('Minta rincian tertulis mengenai biaya konsultasi, asesmen, sesi lanjutan, laporan, alat, pembatalan, dan perjalanan bila ada kunjungan rumah. Bandingkan juga waktu tempuh, jadwal, dan kapasitas keluarga. CDC menjelaskan bahwa layanan intervensi dini mencakup dukungan bagi anak dan keluarga, serta kelayakan ditentukan melalui evaluasi keterampilan. Di Indonesia, mekanisme tiap fasilitas berbeda, sehingga informasi CDC menjadi prinsip umum, bukan aturan pendaftaran lokal.')}
${ul(['Bawa catatan singkat tentang rutinitas dan kekhawatiran keluarga.', 'Tanyakan tujuan yang dapat diamati dan cara mengukur kemajuan.', 'Pastikan profesional menjelaskan manfaat, batasan, risiko, dan alternatif.', 'Minta ringkasan sesi atau latihan rumah yang realistis.', 'Tinjau ulang layanan bila target tidak jelas atau anak terus mengalami stres.'])}
${P(`Keluarga dapat membaca ${L('terapi-okupasi-untuk-anak-cerebral-palsy', 'contoh fokus terapi okupasi')} atau ${L('terapi-fisik-untuk-anak-terlambat-jalan', 'dukungan pada gerak anak')} untuk menyiapkan pertanyaan, bukan untuk mendiagnosis sendiri. Artikel tentang ${L('lembaga-sertifikasi-terapis-anak-di-indonesia', 'sertifikasi terapis')} juga dapat membantu memahami pentingnya kredensial. Jika ada keadaan medis mendesak, nyeri, kejang, kesulitan bernapas, atau risiko keselamatan, hubungi layanan kesehatan, bukan menunggu sesi terapi berikutnya.`)}
${P('Keluarga juga dapat menilai apakah jadwal layanan masuk akal. Anak membutuhkan waktu untuk sekolah, tidur, makan, bermain, dan berinteraksi tanpa target terapi. Jadwal yang terlalu padat dapat membuat anak dan pengasuh kelelahan. Diskusikan prioritas, durasi program, serta kegiatan rumah yang ringan. Latihan rumah seharusnya dapat masuk ke rutinitas seperti membaca buku, berpakaian, berbelanja, atau bermain, bukan menambah daftar tugas yang membuat keluarga merasa gagal.')}
${P('Kolaborasi lintas layanan tidak harus berupa rapat besar. Ringkasan satu halaman sudah cukup untuk menjelaskan tujuan, cara komunikasi anak, bantuan yang berhasil, tanda lelah, serta hal yang sebaiknya dihindari. Dengan persetujuan keluarga, informasi ini dapat dibagikan kepada sekolah atau profesional lain. Jika ada perbedaan pendapat, minta setiap pihak menjelaskan alasan dan bukti pengamatannya. Keluarga boleh mengambil waktu untuk memutuskan dan meminta pendapat kedua.')}
${P(`Layanan yang bermutu memperlakukan orang tua sebagai mitra, bukan sekadar pembayar sesi. ${L('https://www.cdc.gov/act-early/early-intervention/index.html', 'Panduan CDC tentang intervensi dini')} menempatkan anak dan keluarga sebagai penerima dukungan. Prinsip ini relevan meski aturan lokal berbeda. Di Solo, konfirmasi selalu kepada fasilitas resmi tentang jalur rujukan, persyaratan, ketersediaan tenaga, dan biaya terbaru.`)}
${P('Konteks Solo juga perlu dipertimbangkan secara praktis. Waktu tempuh, kemacetan, akses kendaraan, ruang tunggu, dan jadwal sekolah dapat memengaruhi keberlanjutan terapi. Layanan yang sangat jauh tetapi hanya dapat diikuti sesekali belum tentu lebih bermanfaat daripada layanan yang dekat dan konsisten. Tanyakan apakah ada pilihan jadwal pagi atau sore, layanan kelompok, konsultasi daring untuk edukasi orang tua, atau rujukan ketika jadwal penuh. Jangan menganggap semua pilihan tersedia sebelum ada konfirmasi.')}
${P('Bila anak berpindah terapis, minta ringkasan tujuan dan catatan kemajuan yang dapat dibawa ke penyedia berikutnya dengan persetujuan keluarga. Ringkasan tidak perlu memuat semua detail pribadi. Cukup jelaskan kebutuhan utama, strategi yang membantu, strategi yang tidak cocok, alat komunikasi, serta pertanyaan yang masih terbuka. Cara ini mencegah anak mengulang asesmen yang tidak perlu dan membantu profesional baru memahami riwayat dukungan secara lebih utuh.')}
${P('Keluarga boleh menghentikan atau mengubah layanan. Perubahan bukan berarti keluarga gagal dan bukan berarti terapi sebelumnya tidak berguna. Bisa jadi tujuan sudah tercapai, kebutuhan anak berubah, jadwal terlalu berat, atau pendekatan tidak lagi cocok. Sampaikan alasan kepada penyedia bila aman dilakukan, minta rekomendasi transisi, dan simpan dokumen penting. Jika layanan menolak memberikan ringkasan dasar atau menekan keluarga agar terus membayar, pertimbangkan bantuan fasilitas lain.')}
${P('Perhatikan kesejahteraan pengasuh. Mengantar terapi, mengatur pekerjaan, menyiapkan latihan, dan menjawab pertanyaan keluarga besar membutuhkan tenaga. Rencana dukungan yang baik mempertimbangkan kapasitas pengasuh, bukan hanya jadwal ideal di atas kertas. Bicarakan satu atau dua prioritas utama dengan profesional. Anak tetap membutuhkan waktu bermain bebas, tidur cukup, relasi hangat, dan pengalaman menjadi anak tanpa terus dinilai.')}
${P('Simpan pula nomor kontak dan jadwal rujukan secara teratur. Bila penyedia layanan mengubah jam praktik, keluarga perlu tahu siapa yang dapat dihubungi dan kapan harus meminta bantuan lain. Rencana cadangan tidak berarti mengharapkan masalah. Rencana cadangan membuat keluarga tidak panik ketika anak sakit, terapis cuti, atau layanan penuh. Tulis informasi penting di tempat yang dapat diakses pengasuh utama, dengan tetap menjaga kerahasiaan data anak.')}
${P('Saat memilih layanan, tanyakan bagaimana anak dilibatkan dalam membuat pilihan. Anak mungkin belum dapat memberi persetujuan dengan kalimat panjang, tetapi ekspresi, gerak menjauh, menunjuk, atau memilih benda tetap perlu diperhatikan. Profesional dapat memakai pilihan visual dan jeda untuk mengetahui respons anak. Keluarga sebaiknya tidak menerima pendekatan yang menganggap diam sebagai setuju atau tangisan sebagai tanda terapi berhasil.')}
${P(`Bacaan lanjutan yang relevan adalah ${L('terapi-wicara', 'terapi wicara')}, ${L('terapi-okupasi', 'terapi okupasi')}, ${L('perbedaan-terapi-okupasi-dan-terapi-wicara', 'perbedaan terapi okupasi dan terapi wicara')}, dan ${L('macam-macam-terapi-pada-anak', 'macam-macam terapi pada anak')}. Jika satu tautan tidak menjawab kebutuhan keluarga, kembali ke tujuan awal dan minta penjelasan dari fasilitas resmi.`)}
${faqBlock(articles[1].faq)}
`;

articles[2].bodyHtml = `
${P('<strong>Jawaban singkat:</strong> Lebaran anak ABK dapat disiapkan dengan prinsip sederhana: beri informasi lebih awal, sediakan pilihan, atur durasi, siapkan tempat jeda, dan hormati cara anak berkomunikasi. Tujuan perayaan bukan membuat anak terlihat tenang sepanjang waktu, melainkan memberi kesempatan untuk terhubung dan berpartisipasi tanpa dipaksa.')}
<div class="toc"><h3>Daftar Isi</h3><ol><li><a href="#makna">Makna perayaan yang inklusif</a></li><li><a href="#sebelum">Persiapan sebelum Lebaran</a></li><li><a href="#kegiatan">Ide kegiatan</a></li><li><a href="#sensori">Dukungan sensori dan komunikasi</a></li><li><a href="#silaturahmi">Silaturahmi dengan keluarga besar</a></li><li><a href="#keamanan">Keamanan dan pemulihan</a></li><li><a href="#faq">Pertanyaan yang Sering Diajukan</a></li></ol></div>
${H2('makna', 'Lebaran yang inklusif memberi ruang untuk berpartisipasi')}
${P('Perayaan keluarga sering berisi suara ramai, tamu bergantian, pakaian baru, makanan berbeda, perjalanan, dan perubahan jadwal. Bagi sebagian anak, rangkaian perubahan ini menyenangkan. Bagi anak lain, terlalu banyak rangsangan dapat membuat komunikasi dan regulasi lebih sulit. Keluarga tidak perlu memilih antara merayakan atau menghindari semua acara. Yang dapat dilakukan adalah merancang beberapa cara partisipasi sehingga anak memiliki kendali dan orang dewasa memiliki rencana dukungan.')}
${P(`UNICEF menjelaskan bahwa anak penyandang disabilitas memiliki ambisi, kebutuhan belajar, dan hak untuk berpartisipasi seperti anak lain. Prinsip ini dapat diterapkan dalam momen Lebaran: anak dilibatkan sebagai anggota keluarga, bukan hanya dianggap sebagai tamu yang harus mengikuti aturan orang dewasa. ${L('https://www.unicef.org/education/inclusive-education', 'Pendidikan inklusif menurut UNICEF')}, misalnya, menekankan perubahan dukungan dan lingkungan agar anak dapat belajar dan tumbuh bersama. Perayaan juga membutuhkan perubahan lingkungan yang serupa.`)}
${fig('Dokumentasi/artikel/liburan-dengan-anak-berkebutuhan-khusus-wisata-candi.webp', 'Anak dan pendamping mengikuti kegiatan bersama di ruang publik', 'Rencana kegiatan yang lentur membantu keluarga menikmati waktu bersama tanpa memaksa semua anak melakukan hal yang sama.', 936, 702)}
${H2('sebelum', 'Persiapan sebelum Lebaran')}
${P('Mulai dengan kalender sederhana. Tandai hari perjalanan, kunjungan, salat, makan bersama, atau acara keluarga besar. Gunakan foto tempat dan nama orang yang akan ditemui jika anak terbantu oleh informasi visual. Jelaskan bagian yang dapat berubah dengan kalimat singkat. Untuk anak yang menggunakan komunikasi alternatif, siapkan kartu atau alat yang biasa digunakan. Jangan memperkenalkan sistem baru tepat pada hari acara jika belum pernah dilatih.')}
${P('Siapkan tas dukungan yang berisi minuman, makanan aman, pakaian cadangan, alat regulasi, obat sesuai petunjuk, tisu, dan benda yang membantu anak merasa familiar. Rencanakan titik istirahat serta cara pulang lebih awal. Jika keluarga bepergian, berikan pilihan antara berangkat lebih pagi, berhenti di perjalanan, atau mengurangi satu agenda. Persiapan tidak harus mahal. Yang penting adalah membuat situasi dapat diprediksi dan memberi jalan keluar ketika anak membutuhkan jeda.')}
<table><thead><tr><th>Situasi</th><th>Persiapan sederhana</th><th>Pilihan anak</th></tr><tr><td>Rumah ramai</td><td>Sudut tenang, batas jumlah tamu, jadwal singkat</td><td>Ikut menyambut, mengamati, atau beristirahat</td></tr><tr><td>Makan bersama</td><td>Makanan yang familiar dan alat makan sesuai</td><td>Mencicipi, membawa bekal, atau makan di waktu lain</td></tr><tr><td>Salam keluarga</td><td>Jelaskan pilihan sapaan kepada tamu</td><td>Melambaikan tangan, mengucapkan salam, atau tidak kontak fisik</td></tr><tr><td>Perjalanan</td><td>Rute, jeda, pakaian nyaman, dan rencana pulang</td><td>Memilih aktivitas tenang atau tempat duduk bila memungkinkan</td></tr></tbody></table>
${H2('kegiatan', 'Ide kegiatan Lebaran anak ABK')}
${P('Kegiatan yang baik tidak harus berupa acara khusus. Anak dapat membantu menata piring, memilih warna kartu ucapan, memasukkan kue ke wadah, mengambil foto dengan persetujuan, menyiapkan daftar salam, atau memilih lagu yang tenang. Pecah kegiatan menjadi langkah kecil dan tunjukkan contoh. Beri waktu lebih panjang bila anak membutuhkan proses. Pujian sebaiknya menyebut usaha dan pilihan anak, bukan memuji karena anak terlihat normal atau tidak merepotkan.')}
${P('Keluarga juga dapat membuat ritual yang dapat diulang setiap tahun. Misalnya, anak memilih satu makanan, menaruh kartu ucapan di meja, atau membuat album foto singkat. Ritual memberi rasa akrab tanpa mengharuskan anak mengikuti seluruh agenda. Bila anak tidak tertarik, tawarkan alternatif. Partisipasi dapat berarti berada di ruangan selama lima menit, mengamati, atau memilih kapan kembali. Nilai kegiatan ada pada hubungan dan pengalaman, bukan durasi.')}
${fig('Dokumentasi/artikel/penerapan-inklusi-sosial-kegiatan.webp', 'Anak-anak berpartisipasi dalam kegiatan bersama dengan dukungan orang dewasa', 'Peran yang sederhana dan jelas dapat membuat kegiatan keluarga lebih mudah diikuti.', 936, 702)}
${H2('sensori', 'Dukungan sensori dan komunikasi')}
${P('Tidak ada satu daftar sensori yang berlaku untuk semua anak. Ada anak yang merasa terganggu oleh suara petasan, parfum, lampu terang, kerumunan, atau tekstur makanan. Ada pula anak yang mencari gerak dan sentuhan. Amati tanda awal seperti menutup telinga, menjauh, mengulang kata, bergerak lebih cepat, menangis, atau sulit memilih. Tanda tersebut adalah informasi tentang beban situasi, bukan alasan untuk mempermalukan anak.')}
${P('Sampaikan kepada keluarga besar cara berinteraksi yang membantu. Minta mereka tidak memaksa pelukan, cium tangan, mencicipi makanan, atau menjawab pertanyaan secara cepat. Beri anak waktu menanggapi. Jika anak memakai kata, gambar, gestur, atau alat bantu, gunakan cara yang sama. Jangan berbicara tentang diagnosis atau terapi anak di depan tamu tanpa persetujuan. Privasi tetap berlaku dalam perayaan keluarga.')}
${fig('Dokumentasi/artikel/buddy-system-untuk-anak-abk-di-sekolah-kegiatan-bersama.webp', 'Anak mengikuti aktivitas kelompok dengan dukungan teman dan pendamping', 'Dukungan teman sebaya dapat membantu anak merasa aman dan mengetahui langkah kegiatan.', 1200, 900)}
${H2('silaturahmi', 'Membuat silaturahmi lebih mudah')}
${P('Pilih satu atau dua kunjungan yang paling penting, lalu sampaikan durasi kepada tuan rumah. Jika rumah penuh, keluarga dapat mengatur kedatangan di waktu yang lebih sepi. Anak boleh tinggal di dekat orang tua, memilih kursi di tepi ruangan, atau mengamati sebelum bergabung. Orang dewasa yang mendampingi sebaiknya tidak sibuk menjadi tuan rumah dan pengawas sekaligus. Bagilah peran agar satu orang dapat fokus membaca kebutuhan anak.')}
${P(`Aktivitas keluarga dapat dikaitkan dengan ${L('inklusi-sosial', 'inklusi sosial')} dan ${L('teori-inklusi-sosial', 'prinsip partisipasi')} yang sudah dibahas dalam artikel YUKA. Pertanyaan pentingnya bukan "mengapa anak tidak ikut seperti yang lain?" melainkan "dukungan apa yang membuat anak dapat ikut dengan cara yang nyaman?" Cara berpikir ini mengurangi stigma dan membantu keluarga mengubah lingkungan, bukan terus menerus meminta anak menyesuaikan diri sendirian.`)}
${fig('Dokumentasi/artikel/karyawisata-untuk-anak-berkebutuhan-khusus-kegiatan-budaya.webp', 'Kelompok anak dan pendamping mengikuti kegiatan budaya bersama', 'Kunjungan singkat dengan jeda dan pendampingan dapat menjadi pengalaman sosial yang bermakna.', 936, 702)}
${H2('keamanan', 'Keamanan, tanda kewalahan, dan pemulihan')}
${P('Sebelum tamu datang, tentukan orang dewasa yang bertugas mendampingi anak. Simpan benda panas, obat, benda tajam, dan bahan yang dapat tertelan. Periksa pintu, tangga, kolam, jalan, serta tempat yang mungkin membuat anak tersesat. Bila anak cenderung berlari atau kesulitan menyebutkan nama, gunakan rencana keselamatan yang menjaga martabat dan tidak mempermalukannya. Identitas darurat hanya perlu memuat informasi yang benar-benar dibutuhkan.')}
${P('Jika anak mulai kewalahan, kurangi suara dan pertanyaan. Gunakan kalimat pendek, tawarkan dua pilihan, dan pindahkan ke tempat yang lebih tenang. Jangan memaksa anak menjelaskan saat tubuhnya sedang berusaha pulih. Setelah keadaan stabil, berikan minum dan waktu istirahat. Catat pemicu serta dukungan yang berhasil untuk acara berikutnya. Jika ada cedera, gangguan napas, reaksi alergi berat, atau keadaan darurat medis, cari pertolongan kesehatan segera.')}
${ul(['Tanyakan preferensi anak sebelum menentukan agenda.', 'Jelaskan rencana dengan gambar, kata, atau latihan singkat.', 'Sediakan tempat jeda dan rencana pulang lebih awal.', 'Beri pilihan sapaan dan hormati penolakan kontak fisik.', 'Bicarakan kebutuhan anak secara privat dan bermartabat.', 'Nilai keberhasilan dari rasa aman dan partisipasi, bukan kepatuhan total.'])}
${P(`Bacaan tentang ${L('liburan-dengan-anak-berkebutuhan-khusus', 'perjalanan bersama anak berkebutuhan khusus')} dan ${L('cara-melatih-social-skills-anak-autis-di-rumah', 'keterampilan sosial di rumah')} dapat membantu keluarga menyusun strategi sebelum acara. Namun, setiap anak berbeda. Bila perubahan perilaku disertai nyeri, demam, gangguan tidur berat, atau risiko keselamatan, konsultasikan dengan tenaga kesehatan. Perayaan yang inklusif bukan perayaan tanpa tantangan, melainkan perayaan yang menyiapkan dukungan dan menghormati anak.`)}
${P('Anak juga dapat dilibatkan dalam menilai acara setelah selesai. Tanyakan dengan kata, gambar, atau pilihan sederhana: bagian mana yang disukai, kapan terasa terlalu ramai, dan apa yang ingin diubah. Untuk anak yang belum dapat menjawab langsung, perhatikan pola. Apakah anak lebih nyaman saat datang lebih awal? Apakah jeda membantu? Apakah makanan tertentu membuat anak lebih mudah mengikuti kegiatan? Catatan ini dapat menjadi dasar rencana yang lebih baik, tanpa menyalahkan anak atau pengasuh.')}
${P('Orang dewasa perlu menjaga agar foto dan unggahan media sosial tidak mengalahkan kenyamanan anak. Minta persetujuan sebelum memotret, hindari membagikan informasi kesehatan, dan jangan menjadikan momen kewalahan sebagai bahan candaan. Jika keluarga ingin menyimpan kenangan, pilih foto kegiatan yang bermartabat dan simpan untuk lingkaran yang memang perlu melihatnya. Anak berhak memiliki batas privasi, termasuk saat sedang merayakan hari besar.')}
${P(`Inklusi juga mencakup anggota keluarga lain. Saudara kandung dapat diberi penjelasan yang sesuai usia tentang cara menawarkan bantuan dan kapan harus memanggil orang dewasa. Kakek, nenek, dan tamu dapat diberi satu atau dua aturan sederhana sebelum bertemu. ${L('https://www.unicef.org/supply/documents/guidance-including-children-disabilities-education-kit-handbook', 'Panduan UNICEF tentang pelibatan anak penyandang disabilitas')} dapat menjadi rujukan untuk memikirkan hambatan lingkungan dan cara menyesuaikan kegiatan.`)}
${P('Buat pembagian peran sebelum acara. Satu orang dapat mengurus makanan, satu orang menyambut tamu, dan satu orang menjadi pendamping anak. Pembagian ini mengurangi situasi ketika semua orang memberi instruksi sekaligus. Gunakan kata sandi keluarga untuk meminta bantuan atau pulang. Jika anak memiliki cara komunikasi tertentu, pastikan pendamping lain mengetahui cara merespons tanpa menebak-nebak atau menyalahkan anak.')}
${P('Perayaan juga dapat dibuat lebih mudah dengan mengurangi agenda yang tidak penting. Tidak semua tamu harus ditemui pada satu hari. Keluarga dapat mengirim salam melalui pesan suara, video singkat, atau kartu jika kunjungan langsung terlalu berat. Anak dapat memilih apakah ingin tampil di video atau tidak. Pilihan jarak jauh bukan berarti hubungan keluarga kurang dekat. Ini adalah cara menyesuaikan media agar lebih banyak orang dapat terhubung.')}
${P('Bila makanan menjadi bagian penting acara, siapkan menu yang aman dan komunikasikan alergi atau pantangan dengan jelas. Jangan menjadikan anak tontonan saat mencoba makanan baru. Beri porsi kecil, alat makan yang dikenal, dan waktu makan yang cukup. Untuk anak yang membutuhkan pola makan tertentu, keluarga dapat membawa bekal tanpa harus meminta maaf. Tamu perlu menghormati keputusan tersebut.')}
${P('Keluarga dapat menutup acara dengan rutinitas yang menenangkan, misalnya mandi, membaca buku, mendengarkan suara yang disukai, atau melihat jadwal esok hari. Kelelahan setelah acara dapat muncul beberapa jam kemudian. Beri kesempatan tidur dan kurangi tuntutan pada hari berikutnya. Catatan singkat tentang apa yang berhasil akan lebih berguna daripada menyimpulkan bahwa anak nakal atau tidak mau bersosialisasi. Dengan persiapan, Lebaran dapat menjadi ruang belajar hubungan yang hangat bagi seluruh keluarga.')}
${P('Bicarakan persetujuan dengan cara yang sesuai kemampuan anak. Persetujuan dapat berupa mendekat, memilih, mengangguk, atau menunjukkan kartu. Diam, membeku, dan menjauh bukan tanda setuju. Tamu perlu menerima batas anak tanpa meminta orang tua membujuk. Prinsip ini berlaku untuk foto, pelukan, makanan, percakapan, dan kegiatan ibadah. Menghormati batas bukan mengurangi adab, melainkan mengajarkan hubungan yang aman dan saling menghargai.')}
${P('Orang dewasa juga dapat menunjukkan contoh dengan meminta izin sebelum mengambil foto atau menyentuh barang anak. Bila anak berubah pikiran, keputusan itu tetap dihormati. Dengan begitu, perayaan tidak hanya ramai, tetapi juga menjadi latihan nyata tentang komunikasi, batas pribadi, dan kepedulian yang dapat dibawa anak ke sekolah serta lingkungan lain.')}
${P(`Keluarga dapat membaca ${L('prinsip-inklusi-sosial', 'prinsip inklusi sosial')}, ${L('penerapan-inklusi-sosial', 'penerapan inklusi sosial')}, ${L('pendidikan-inklusi', 'pendidikan inklusi')}, dan ${L('program-ramadhan-yuka-2026', 'contoh kegiatan Ramadan YUKA')} untuk membandingkan cara kegiatan dirancang. Gagasan tersebut tetap perlu disesuaikan dengan usia, budaya keluarga, komunikasi, dan kenyamanan anak.`)}
${faqBlock(articles[2].faq)}
`;

for (const a of articles) {
  const html = renderArticlePage(a);
  const out = path.join(OUT, `${a.slug}.html`);
  fs.writeFileSync(out, html);
  console.log(`WROTE ${out} ${html.length} bytes`);
}
